### ISSUE TITLE
Add ability to change post flair

### ISSUE THREAD

**Issue by PitchforkAssistant** [PitchforkAssistant/devvit-flair-assistant#2]
Likely identical to the way userFlair is defined, just the same for postFlair. Config generator will also need to be updated. 

There's also the question of what to do with the existing `clearPostFlair` property. Does it get deprecated? If not, which one takes priority?

**Comment by epicmindwarp** [comment]
clearPostFlair is fine to stay, because some people will still want it to clear.

**Comment by PitchforkAssistant** [comment]
> clearPostFlair is fine to stay, because some people will still want it to clear.

Should I also add a clearUserFlair toggle? That might be the most elegant solution, since that would make the PostFlair and UserFlair configs match up.

**Comment by PitchforkAssistant** [comment]
Implemented as of commit c2b2a227cd1f068253b35ce7b82509c426e83121
